config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,		:validate => true
	attribute :email,		:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,		:validate => true
	attribute :nickname,	:captcha => true

	def headers
	{
		:subject => "Contact Form",
		:to => "gxenos95@gmail.com",
		:from => %("#{name}" <#{email}>)
	}
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Published!"
		else
			render 'new', notice: "Unable to Publish!"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Your article was succefully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
			@post = Post.friendly.find(params[:id])
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@projects = Project.all.order("created_at desc")
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "The project was succefully published!"
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "The project was succefully published!"
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private

	def find_project
		@project = Project.friendly.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:title, :description, :slug)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
		@projects = Project.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true,
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Contact</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for your message.</h1>
	<p>I ll get back to you soon...</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Contact</h1>
	
	<div class="skinny_wrapper wrapper_padding">
		<%= form_for @contact do |f| %>
			<%= f.label :name %><br>
			<%= f.text_field :name, required: true %>
			
			<br>

			<%= f.label :email %><br>
			<%= f.email_field :email, required: true %>

			<br>

			<%= f.label :message %><br>
			<%= f.text_area :message, as: :text %>

			<div class="hidden">
				<%= f.label :nickname %><br>
				<%= f.text_field :nickname, hint: 'leave this field blank' %>
			</div>

			<%= f.submit 'Send Message', class:"button" %>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>George Xenos</title>
	<link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
		<%= link_to "George Xenos",root_path, class:"name" %>
		<nav>
			<%= link_to "Articles",posts_path %>
			<%= link_to "Projects",projects_path %>
			<%= link_to "Contact",new_contact_path %>
			<% if user_signed_in? %>
				<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
			<% end %>
		</nav>
	</header>
	
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% elsif alert %>
		<p class="alert"><%= alert %></p>
	<% end %>


<%= yield %>

<footer id="main_footer">
	<p class="copyright">&copy; 2015 George Xenos</p>
		
</footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'georgexenosblog';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count,"error") %>prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
		<% end %>

		<%= f.label :title %><br>
		<%= f.text_field :title %>

		<br>
		<br>

		<%= f.label :content, "Write your article here." %><br>
		<%= f.text_area :content %>

		<br>
		<br>

		<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class = "skinny_wrapper wrapper_padding">
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Blog Posts</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
	<div class="post">
		<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
		<h2><a href="#"><%= link_to post.title, post %></a></h2>
		<hr>
	</div>
	<% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

<div class = "skinny_wrapper wrapper_padding">

<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
		<header>
			<p class="date"><%= @post.created_at.strftime('%A,%b %d') %></p>
			<h1><%= @post.title %></h1>
			<hr>
		</header>

		<div id="content">
			<%= markdown @post.content %>
		</div>

		<% if user_signed_in? %>
			<div id="admin_links">
				<%= link_to "Edit Post", edit_post_path(@post) %>
				<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>
			</div>
		<% end %>

		<hr>

		<div id="share_box">
			<p>Share First Post</p>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-google-plus"></i></a>
		</div>

		<hr>

		<%= render 'disqus' %>

	</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count,"error") %>prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
		<% end %>

		<%= f.label :title %><br>
		<%= f.text_field :title %>

		<br>
		<br>

		<%= f.label :description, "Write your article here." %><br>
		<%= f.text_area :description %>

		<br>
		<br>

		<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>
<div class = "skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Projects</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @projects.each do |project| %>
	<div class="post">
		<p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
		<h2><a href="#"><%= link_to project.title, project %></a></h2>
		<hr>
	</div>
	<% end %>
</div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>
<div class = "skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
		<header>
			<p class="date"><%= @project.created_at.strftime('%A,%b %d') %></p>
			<h1><%= @project.title %></h1>
			<hr>
		</header>

		<div id="content">
			<%= markdown @project.description %>
		</div>
		
		<% if user_signed_in? %>
			<div id="admin_links">
				<%= link_to "Edit", edit_project_path(@project) %>
				<%= link_to "Delete",project_path(@project), method: :delete,data: { confirm: "Are you sure?"} %>
			</div>
		<% end %>
		

		

		<hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>About</h2>
		<hr>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> <p>Praesentium aperiam temporibus, velit, fugit enim omnis nulla, quidem deleniti.</p><p>Ex blanditiis iusto eligendi maiores assumenda culpa error accusantium obcaecati sit corporis.</p>
	</div>
	<div class="col-2 homepage_content">
		<h2>Blog Posts</h2>
		<hr>

		<% @posts.each do |post| %>
		<h3><a href="#"><%= link_to post.title, post %></a></h3>
		<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
		<% end %>
	</div>
	<div class="col-3 homepage_content">
		<h2>Projects</h2>
		<hr>

		<% @projects.each do |project| %>
		<h3><a href="#"><%= link_to project.title, project %></a></h3>
		<p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
		<% end %>
	</div>
</div>